// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu-GFCxmBMlln8ceiJedrffOZ3x1BHKC4',
    appId: '1:288271871324:web:bd2ff9e09642f24509a599',
    messagingSenderId: '288271871324',
    projectId: 'emart-fe09a',
    authDomain: 'emart-fe09a.firebaseapp.com',
    storageBucket: 'emart-fe09a.appspot.com',
    measurementId: 'G-6RRR2Z7NB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOfG4M9VD2IWIAuCaFPCOFNNaxeapFhQs',
    appId: '1:288271871324:android:0a524ac66244f40e09a599',
    messagingSenderId: '288271871324',
    projectId: 'emart-fe09a',
    storageBucket: 'emart-fe09a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJs6-QAUqEKBCcGyRZx5wO6BTllFuLIL8',
    appId: '1:288271871324:ios:568dde4777790f5109a599',
    messagingSenderId: '288271871324',
    projectId: 'emart-fe09a',
    storageBucket: 'emart-fe09a.appspot.com',
    androidClientId: '288271871324-surfghihqblm8tdmm1uhgq74gtuen5bs.apps.googleusercontent.com',
    iosClientId: '288271871324-47b5u9c2l2jck3enki0tq6gfoira8tj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJs6-QAUqEKBCcGyRZx5wO6BTllFuLIL8',
    appId: '1:288271871324:ios:00ad30f366168f3e09a599',
    messagingSenderId: '288271871324',
    projectId: 'emart-fe09a',
    storageBucket: 'emart-fe09a.appspot.com',
    androidClientId: '288271871324-surfghihqblm8tdmm1uhgq74gtuen5bs.apps.googleusercontent.com',
    iosClientId: '288271871324-5jh7o7c1h91ncv62kk873om6num26hjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
